### ISSUE TITLE
Suggestion: Allow user to set location of ttd_palette.json

### ISSUE THREAD

**Issue by 2TallTyler** [mattkimber/gorender#2]
Hello,

Is there a command line flag to set the location of ttd_palette.json? I understand it defaults to files/, but this is relative to the working directory of the command line or the location of the makefile (at least the one I use).

The latter is easily (if clumsily) solved by including a copy of files/ttd_palette.json relative to the makefile in each [project folder](https://github.com/2TallTyler/garbage-trucks), but adding a flag to set an absolute path for this file (or if said flag already exists, specifying it in the readme) would be a welcome addition to any future Gorender releases.

Tyler

**Comment by mattkimber** [comment]
There is now a new `-palette` parameter, for precisely this.

**Comment by 2TallTyler** [comment]
Excellent, thanks!
