### ISSUE TITLE
Suggestion: Ground sprites with partial transparency

### ISSUE THREAD

**Issue by 2TallTyler** [mattkimber/gorender#3]
Hello,

I'm experimenting with drawing driveways but leaving the rest of the ground tile transparent to show a separate ground sprite underneath (the grass sprite from the base graphics set).

Currently, Gorender treats this as a 3D shape and applies highlights and shading to the sides of the driveway voxels.

![r1_fulton_noground_8bpp](https://user-images.githubusercontent.com/55058389/99021723-4a968080-252f-11eb-93a8-2d65af8aee54.png)

It would be useful if there was a way to avoid rendering these ground voxels as 3D shapes, like with the tiled_normals setting. My suggestion would be to use the blue background voxels as below. At the moment, Gorender seems to ignore voxels of this color completely (the above sprite is rendered from the model below).

![transparent_ground](https://user-images.githubusercontent.com/55058389/99022070-05bf1980-2530-11eb-9d8b-918e12de0d9f.png)

Another option might be a manifest setting to not consider voxels at z=0 for 3D shading.

Thoughts?

**Comment by mattkimber** [comment]
There's a somewhat hidden feature you can use for this, which doesn't work in _exactly_ this way but will give you the necessary results related to normals. If you add `"non_renderable": true` to a range in `ttd_palette.json` the raycasting and normal calculation will be done as normal, but when the object is shaded it will output the pixels as transparent.

The subtle difference with this feature is the "non-renderable" pixels still occlude ones behind them. I think for what you're doing it will work fine, as you don't want to render the edges of paths.

I'll update the default shipped `ttd_palette.json` to the one that comes from Timberwolf's Trains, which has more accurate colour ranges and lets you use MagicaVoxel palette index 255 as this non-renderable transparent colour. I've also added a new feature to manifests which lets you consider the base voxels below an object as "solid" for the purposes of calculating normals, which should improve the lighting and shading of single voxel deep driveways and the like.

Give v1.2.0 a try once it's built and released, and let me know if the non-renderable option does what you want or if a non-occluding variant is also needed.

**Comment by 2TallTyler** [comment]
Thanks. Will try this soon.

**Comment by 2TallTyler** [comment]
I've tried the solid base manifest flag and it does exactly what I want.

I do want to try some sloped tile rendering using non-renderable colors. If I'm reading your post right, blue 255 voxels will block voxels behind them from being rendered, which would be very helpful indeed. I'll report back on this.

**Comment by 2TallTyler** [comment]
Sloped houses are a go!

![sloped_voxels](https://user-images.githubusercontent.com/55058389/100777436-cf104c80-33d3-11eb-955e-e2663d05eb11.PNG)

![r1_stiles_8bpp](https://user-images.githubusercontent.com/55058389/100777534-f0713880-33d3-11eb-9312-f60d571dcfd3.png)

Rotation and recoloring give great variety.

![sloped_houses](https://user-images.githubusercontent.com/55058389/100776936-25c95680-33d3-11eb-8aae-eb0f7383572f.PNG)

Coding the slope and rotation checks for the house and road tiles will be a completely separate challenge!

Thanks for all your work on this great workflow.
